name: Check code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: |
    ${{ github.workflow }} - ${{ github.head_ref || github.ref  || github.sha || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - name: Setup PHP
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: '8.3'
          extensions: pgsql, gd, curl, mbstring, xml, zip, bcmath, intl
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@3.0.0

#      - name: Run static analysis
#        run: ./vendor/bin/phpstan analyse
#        if: ${{ always() }}

#      - name: Run tests
#        run: ./vendor/bin/phpunit tests
#        if: ${{ always() }}

#      - name: Run rector
#        run: ./vendor/bin/rector --dry-run
#        if: ${{ always() }}

      - name: Run linter
        run: ./vendor/bin/pint --test
        if: ${{ always() }}
